name: xpreppg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  connectivity_plus: ^7.0.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1   # âœ… Correct version - stable

flutter:
  uses-material-design: true
